units:
  - path: /sub_ecu/planning/sub_ecu_in_lane_moderate_stop_available
    type: and
    list:
      - { type: link, link: /sub_ecu/planning/topic_status/trajectory/warn-to-ok }

  - path: /sub_ecu/planning/topic_status/trajectory/warn-to-ok
    type: warn-to-ok
    item:
      type: link
      link: /sub_ecu/planning/topic_status/trajectory

  - path: /sub_ecu/planning/topic_status/trajectory
    type: diag
    node: topic_state_monitor_trajectory
    name: topic_status
    timeout: 3.0
    # latch: 0.0
