units:
  - path: /sub_ecu/sensing/sub_ecu_in_lane_moderate_stop_available
    type: and
    list:
      - { type: link, link: /sub_ecu/sensing/imu/gyro_bias_scale_validation/warn-to-ok }
      - { type: link, link: /sub_ecu/sensing/imu/rate_bound_check/warn-to-ok }

  - path: /sub_ecu/sensing/imu/gyro_bias_scale_validation/warn-to-ok
    type: warn-to-ok
    item:
      type: link
      link: /sub_ecu/sensing/imu/gyro_bias_scale_validation

  - path: /sub_ecu/sensing/imu/rate_bound_check/warn-to-ok
    type: warn-to-ok
    item:
      type: link
      link: /sub_ecu/sensing/imu/rate_bound_check

  - path: /sub_ecu/sensing/imu/gyro_bias_scale_validation
    type: diag
    node: gyro_bias_scale_validator
    name: gyro_bias_scale_validator
    timeout: 3.0
    # latch: 0.0

  - path: /sub_ecu/sensing/imu/rate_bound_check
    type: diag
    node: /sensing/imu/tamagawa/tag_can_driver
    name: rate bound check
    timeout: 3.0
    # latch: 0.0
