units:
  - path: /sub_ecu/vehicle/sub_ecu_in_lane_moderate_stop_available
    type: and
    list:
      - { type: link, link: /sub_ecu/vehicle/topic_status/actuation_command/warn-to-ok }
      - { type: link, link: /sub_ecu/vehicle/topic_status/velocity/warn-to-ok }
      - { type: link, link: /sub_ecu/vehicle/topic_status/steering/warn-to-ok }
      - { type: link, link: /sub_ecu/vehicle/vcu_not_authenticated/warn-to-ok }
      - { type: link, link: /sub_ecu/vehicle/t4_vcu_version_check/warn-to-ok }

  - path: /sub_ecu/vehicle/topic_status/actuation_command/warn-to-ok
    type: warn-to-ok
    item:
      type: link
      link: /sub_ecu/vehicle/topic_status/actuation_command

  - path: /sub_ecu/vehicle/topic_status/velocity/warn-to-ok
    type: warn-to-ok
    item:
      type: link
      link: /sub_ecu/vehicle/topic_status/velocity

  - path: /sub_ecu/vehicle/topic_status/steering/warn-to-ok
    type: warn-to-ok
    item:
      type: link
      link: /sub_ecu/vehicle/topic_status/steering

  - path: /sub_ecu/vehicle/vcu_not_authenticated/warn-to-ok
    type: warn-to-ok
    item:
      type: link
      link: /sub_ecu/vehicle/vcu_not_authenticated

  - path: /sub_ecu/vehicle/t4_vcu_version_check/warn-to-ok
    type: warn-to-ok
    item:
      type: link
      link: /sub_ecu/vehicle/t4_vcu_version_check

  - path: /sub_ecu/vehicle/topic_status/actuation_command
    type: diag
    node: topic_state_monitor_control_command_actuation_cmd
    name: topic_status
    timeout: 1.0
    latch: 0.0

  - path: /sub_ecu/vehicle/topic_status/velocity
    type: diag
    node: topic_state_monitor_vehicle_status_velocity_status
    name: topic_status
    timeout: 1.0
    latch: 0.0

  - path: /sub_ecu/vehicle/topic_status/steering
    type: diag
    node: topic_state_monitor_vehicle_status_steering_status
    name: topic_status
    timeout: 1.0
    latch: 0.0

  - path: /sub_ecu/vehicle/vcu_not_authenticated
    type: diag
    node: j6_interface
    name: vcu_not_authenticated
    timeout: 3.0
    latch: 0.0

  - path: /sub_ecu/vehicle/t4_vcu_version_check
    type: diag
    node: j6_interface
    name: t4-vcu_version_check
    timeout: 3.0
    latch: 0.0
