# This file is managed by sync-params workflow.
# Keys marked with '{OVERRIDE}' or '# {OVERRIDE: reason}' are persisted as variant overrides.
# 'reason' can be any single-line text without braces.
# To keep local changes, annotate fields with '# {OVERRIDE}' or '# {OVERRIDE: reason}'.
#
# Source: https://github.com/autowarefoundation/autoware_universe/blob/98ef5348b6e9e22f9ca69c9f841655bd7fc44610/localization/yabloc/yabloc_image_processing/config/segment_filter.param.yaml

/**:
  ros__parameters:
    min_segment_length:  1.5    # if it is negative, it is unlimited
    max_segment_distance:  30.0 # if it is negative, it is unlimited
    max_lateral_distance: 10.0  # if it is negative, it is unlimited
    publish_image_with_segment_for_debug: true
    max_range: 20.0
    image_size: 800 # debug
