/**:
  ros__parameters:
    input_frame: "base_link"
    output_frame: "base_link"
    min_x: -10.0
    max_x: 10.0
    min_y: 0.0
    max_y: 7.5
    min_z: -5.0
    max_z: 5.0
    negative: False
    processing_time_threshold_sec: 0.01
