/**:
  ros__parameters:
    sync_queue_size: 20
    precision_threshold_to_judge_overlapped: 0.4
    recall_threshold_to_judge_overlapped: 0.5
    remove_overlapped_unknown_objects: true
    base_link_frame_id: base_link
    # class based priority mode for PriorityMode::ClassBased,
    # The value should be one of 0: Object0, 1: Object1, 2: Confidence
    class_based_priority_matrix:
    #UNKNOWN, CAR, TRUCK, BUS,  TRAILER, MOTORBIKE, BICYCLE,PEDESTRIAN -> Object0
      [2,       0,   0,     0,    0,       0,         0,      0,         #UNKNOWN
       0,       0,   0,     0,    0,       0,         0,      0,         #CAR
       0,       0,   0,     0,    0,       0,         0,      0,         #TRUCK
       0,       0,   0,     0,    0,       0,         0,      0,         #BUS
       0,       0,   0,     0,    0,       0,         0,      0,         #TRAILER
       0,       0,   0,     0,    0,       0,         1,      1,         #MOTORBIKE
       0,       0,   0,     0,    0,       0,         0,      1,         #BICYCLE
       0,       0,   0,     0,    0,       0,         0,      0]         #PEDESTRIAN -> object1
    message_timeout_sec: 1.0
    initialization_timeout_sec: 10.0
