perception:
  - repository: autowarefoundation/autoware_universe
    ref: main
    files:
      # Perception
      - # Source param path in source repository.
        source: perception/autoware_image_object_locator/config/bbox_object_locator.param.yaml
        # List of param paths in current repository that are variants of the source param path.
        # Variant files should have the same yaml file layout as the source file and only differ in the parameters.
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/camera_vru_detection/near_range_camera_vru_detector.param.yaml
      - source: perception/autoware_euclidean_cluster/config/euclidean_cluster.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/clustering/euclidean_cluster.param.yaml
      - source: perception/autoware_detected_object_validation/config/obstacle_pointcloud_based_validator.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/detected_object_validation/obstacle_pointcloud_based_validator.param.yaml
      - source: perception/autoware_detected_object_validation/config/occupancy_grid_based_validator.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/detected_object_validation/occupancy_grid_based_validator.param.yaml
      - source: perception/autoware_detection_by_tracker/config/detection_by_tracker.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/detection_by_tracker/detection_by_tracker.param.yaml
      - source: perception/autoware_image_projection_based_fusion/config/fusion_common.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/fusion_common.param.yaml
      - source: perception/autoware_image_projection_based_fusion/config/pointpainting_common.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/pointpainting_common.param.yaml
      - source: perception/autoware_image_projection_based_fusion/config/roi_cluster_fusion.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/roi_cluster_fusion.param.yaml
      - source: perception/autoware_image_projection_based_fusion/config/roi_detected_object_fusion.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/roi_detected_object_fusion.param.yaml
      - source: perception/autoware_image_projection_based_fusion/config/roi_pointcloud_fusion.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/roi_pointcloud_fusion.param.yaml
      #
      # irregular_object_detector.param.yaml omitted;
      # It is actually a mix of 3 different param files. Needs refactoring to track via this workflow.
      #
      - source: perception/autoware_bevfusion/config/bevfusion_camera_lidar.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/lidar_model/bevfusion_camera_lidar.param.yaml
      - source: perception/autoware_bevfusion/config/common_bevfusion.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/lidar_model/bevfusion_common.param.yaml
      - source: perception/autoware_bevfusion/config/bevfusion_lidar.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/lidar_model/bevfusion_lidar.param.yaml
      - source: perception/autoware_lidar_centerpoint/config/centerpoint_common.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_common.param.yaml
      - source: perception/autoware_lidar_centerpoint/config/centerpoint_sigma.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_sigma.param.yaml
      - source: perception/autoware_lidar_centerpoint/config/centerpoint_tiny.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint_tiny.param.yaml
      - source: perception/autoware_lidar_centerpoint/config/centerpoint.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/lidar_model/centerpoint.param.yaml
      - source: perception/autoware_image_projection_based_fusion/config/pointpainting.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/lidar_model/pointpainting.param.yaml
      - source: perception/autoware_lidar_transfusion/config/transfusion_common.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/lidar_model/transfusion_common.param.yaml
      - source: perception/autoware_lidar_transfusion/config/transfusion.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/lidar_model/transfusion.param.yaml
      - source: perception/autoware_detected_object_validation/config/object_lanelet_filter.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/object_filter/object_lanelet_filter.param.yaml
          - path: autoware_launch/config/perception/object_recognition/detection/object_filter/radar_lanelet_filter.param.yaml
      - source: perception/autoware_detected_object_validation/config/object_position_filter.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/object_filter/object_position_filter.param.yaml
      - source: perception/autoware_object_merger/config/data_association_matrix.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/object_merger/data_association_matrix.param.yaml
      - source: perception/autoware_object_merger/config/object_association_merger.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/object_merger/ml_camera_lidar_object_association_merger.param.yaml
      - source: perception/autoware_object_merger/config/overlapped_judge.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/object_merger/overlapped_judge.param.yaml
      #
      # pointcloud_map_filter.param.yaml omitted. The 'param file' is completely interpreted by launcher.
      #
      - source: perception/autoware_object_sorter/config/detected_object_sorter.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/detection/radar_filter/detected_object_sorter.param.yaml
      - source: perception/autoware_map_based_prediction/config/map_based_prediction.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/prediction/map_based_prediction.param.yaml
      - source: perception/autoware_multi_object_tracker/config/data_association_matrix.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/data_association_matrix.param.yaml
      - source: perception/autoware_multi_object_tracker/config/input_channels.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/input_channels.param.yaml
      - source: perception/autoware_multi_object_tracker/config/multi_object_tracker_node.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/tracking/multi_object_tracker/multi_object_tracker_node.param.yaml
      - source: perception/autoware_detected_object_validation/config/tracked_object_lanelet_filter.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/tracking/radar_object_tracker/tracked_object_lanelet_filter.param.yaml
      - source: perception/autoware_object_sorter/config/tracked_object_sorter.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/tracking/radar_object_tracker/tracked_object_sorter.param.yaml
      - source: perception/autoware_tracking_object_merger/config/data_association_matrix.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/tracking/tracking_object_merger/data_association_matrix.param.yaml
      - source: perception/autoware_tracking_object_merger/config/decorative_tracker_merger_policy.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/tracking/tracking_object_merger/decorative_tracker_merger_policy.param.yaml
      - source: perception/autoware_tracking_object_merger/config/decorative_tracker_merger.param.yaml
        variants:
          - path: autoware_launch/config/perception/object_recognition/tracking/tracking_object_merger/decorative_tracker_merger.param.yaml
      # Perception/obstacle_segmentation
      # Perception/occupancy_grid_map
      # Perception/traffic_light_recognition

localization: []
map:
  - repository: autowarefoundation/autoware_core
    ref: main
    files:
      - source: map/autoware_map_loader/config/lanelet2_map_loader.param.yaml
        variants:
          - path: autoware_launch/config/map/lanelet2_map_loader.param.yaml
      - source: map/autoware_map_loader/config/pointcloud_map_loader.param.yaml
        variants:
          - path: autoware_launch/config/map/pointcloud_map_loader.param.yaml
      - source: map/autoware_map_projection_loader/config/map_projection_loader.param.yaml
        variants:
          - path: autoware_launch/config/map/map_projection_loader.param.yaml
  - repository: autowarefoundation/autoware_universe
    ref: main
    files:
      - source: map/autoware_map_tf_generator/config/map_tf_generator.param.yaml
        variants:
          - path: autoware_launch/config/map/map_tf_generator.param.yaml

planning:
  - repository: autowarefoundation/autoware_core
    ref: main
    files:
      - source: planning/autoware_velocity_smoother/config/Analytical.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/autoware_velocity_smoother/Analytical.param.yaml
      - source: planning/autoware_velocity_smoother/config/JerkFiltered.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/autoware_velocity_smoother/JerkFiltered.param.yaml
      - source: planning/autoware_velocity_smoother/config/L2.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/autoware_velocity_smoother/L2.param.yaml
      - source: planning/autoware_velocity_smoother/config/Linf.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/autoware_velocity_smoother/Linf.param.yaml
      - source: planning/autoware_core_planning/config/autoware_velocity_smoother/velocity_smoother.param.yaml
        # planning/autoware_velocity_smoother/config/default_velocity_smoother.param.yaml ?
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/autoware_velocity_smoother/velocity_smoother.param.yaml
      - source: planning/autoware_core_planning/config/common.param.yaml
        # planning/autoware_velocity_smoother/config/default_common.param.yaml ?
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/common.param.yaml
      - source: planning/autoware_core_planning/config/nearest_search.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/nearest_search.param.yaml

  - repository: autowarefoundation/autoware_universe
    ref: main
    files:
      # Planning/mission_planner
      - source: planning/autoware_mission_planner_universe/config/mission_planner.param.yaml
        variants:
          - path: autoware_launch/config/planning/mission_planning/mission_planner/mission_planner.param.yaml
      # Planning/neural_net_planner
      - source: planning/autoware_trajectory_optimizer/config/plugins/trajectory_extender.param.yaml
        variants:
          - path: autoware_launch/config/planning/neural_net_planner/trajectory_optimizer_plugins/trajectory_extender.param.yaml
      - source: planning/autoware_trajectory_optimizer/config/plugins/trajectory_kinematic_feasibility_enforcer.param.yaml
        variants:
          - path: autoware_launch/config/planning/neural_net_planner/trajectory_optimizer_plugins/trajectory_kinematic_feasibility_enforcer.param.yaml
      - source: planning/autoware_trajectory_optimizer/config/plugins/trajectory_mpt_optimizer.param.yaml
        variants:
          - path: autoware_launch/config/planning/neural_net_planner/trajectory_optimizer_plugins/trajectory_mpt_optimizer.param.yaml
      - source: planning/autoware_trajectory_optimizer/config/plugins/trajectory_point_fixer.param.yaml
        variants:
          - path: autoware_launch/config/planning/neural_net_planner/trajectory_optimizer_plugins/trajectory_point_fixer.param.yaml
      - source: planning/autoware_trajectory_optimizer/config/plugins/trajectory_qp_smoother.param.yaml
        variants:
          - path: autoware_launch/config/planning/neural_net_planner/trajectory_optimizer_plugins/trajectory_qp_smoother.param.yaml
      - source: planning/autoware_trajectory_optimizer/config/plugins/trajectory_spline_smoother.param.yaml
        variants:
          - path: autoware_launch/config/planning/neural_net_planner/trajectory_optimizer_plugins/trajectory_spline_smoother.param.yaml
      - source: planning/autoware_trajectory_optimizer/config/plugins/trajectory_temporal_mpt_optimizer.param.yaml
        variants:
          - path: autoware_launch/config/planning/neural_net_planner/trajectory_optimizer_plugins/trajectory_temporal_mpt_optimizer.param.yaml
      - source: planning/autoware_trajectory_optimizer/config/plugins/trajectory_velocity_optimizer.param.yaml
        variants:
          - path: autoware_launch/config/planning/neural_net_planner/trajectory_optimizer_plugins/trajectory_velocity_optimizer.param.yaml
      - source: planning/autoware_diffusion_planner/config/diffusion_planner.param.yaml
        variants:
          - path: autoware_launch/config/planning/neural_net_planner/diffusion_planner.param.yaml
      - source: planning/autoware_trajectory_modifier/config/trajectory_modifier.param.yaml
        variants:
          - path: autoware_launch/config/planning/neural_net_planner/trajectory_modifier.param.yaml
      - source: planning/autoware_trajectory_optimizer/config/trajectory_optimizer.param.yaml
        variants:
          - path: autoware_launch/config/planning/neural_net_planner/trajectory_optimizer.param.yaml
      # Planning/parking
      - source: planning/autoware_freespace_planner/config/freespace_planner.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/parking/freespace_planner/freespace_planner.param.yaml
      # Planning/scenario_planning/common
      - source: planning/autoware_hazard_lights_selector/config/hazard_lights_selector.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/autoware_hazard_lights_selector/hazard_lights_selector.param.yaml
      - source: planning/planning_validator/autoware_planning_validator_intersection_collision_checker/config/intersection_collision_checker.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/planning_validator/intersection_collision_checker.param.yaml
      - source: planning/planning_validator/autoware_planning_validator_latency_checker/config/latency_checker.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/planning_validator/latency_checker.param.yaml
      - source: planning/planning_validator/autoware_planning_validator_rear_collision_checker/config/rear_collision_checker.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/planning_validator/rear_collision_checker.param.yaml
      - source: planning/planning_validator/autoware_planning_validator_trajectory_checker/config/trajectory_checker.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/planning_validator/trajectory_checker.param.yaml
      - source: planning/planning_validator/autoware_planning_validator/config/planning_validator.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml
      - source: planning/autoware_costmap_generator/config/costmap_generator.param.yaml
        variants:
          - path: autoware_launch/config/planning/scenario_planning/common/costmap_generator.param.yaml
      # Planning/scenario_planning/lane_driving/behavior_planning
      # Planning/scenario_planning/lane_driving/motion_planning

control: []
system: []
vehicle: []
simulator: []
