- repository: autowarefoundation/autoware.universe
  files:
    # tier4_autoware_api_launch

    # tier4_control_launch

    # tier4_localization_launch

    # tier4_map_launch

    # tier4_perception_launch

    # tier4_planning_launch
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/rtc_auto_mode_manager/rtc_auto_mode_manager.param.yaml
      dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/behavior_planning/rtc_auto_mode_manager/rtc_auto_mode_manager.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml
      dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml

    # tier4_sensing_launch

    # tier4_simulator_launch

    # tier4_system_launch

    # tier4_vehicle_launch
