- repository: autowarefoundation/autoware.universe
  files:
    - source: launch/tier4_perception_launch/config/object_recognition/tracking/multi_object_tracker/data_association_matrix.param.yaml
      dest: tier4_perception_launch/config/object_recognition/tracking/multi_object_tracker/data_association_matrix.param.yaml
    - source: launch/tier4_perception_launch/config/object_recognition/detection/pointcloud_map_filter.param.yaml
      dest: tier4_perception_launch/config/object_recognition/detection/pointcloud_map_filter.param.yaml
    - source: launch/tier4_perception_launch/config/object_recognition/detection/object_position_filter.param.yaml
      dest: tier4_perception_launch/config/object_recognition/detection/object_position_filter.param.yaml
    - source: launch/tier4_perception_launch/config/object_recognition/detection/object_lanelet_filter.param.yaml
      dest: tier4_perception_launch/config/object_recognition/detection/object_lanelet_filter.param.yaml
    - source: launch/tier4_perception_launch/config/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml
      dest: tier4_perception_launch/config/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml
    - source: launch/tier4_perception_launch/config/obstacle_segmentation/ground_segmentation/elevation_map_parameters.yaml
      dest: tier4_perception_launch/config/obstacle_segmentation/ground_segmentation/elevation_map_parameters.yaml
    - source: launch/tier4_localization_launch/config/localization_error_monitor.param.yaml
      dest: tier4_localization_launch/config/localization_error_monitor.param.yaml
    - source: launch/tier4_localization_launch/config/ndt_scan_matcher.param.yaml
      dest: tier4_localization_launch/config/ndt_scan_matcher.param.yaml
    - source: launch/tier4_localization_launch/config/voxel_grid_filter.param.yaml
      dest: tier4_localization_launch/config/voxel_grid_filter.param.yaml
    - source: launch/tier4_localization_launch/config/random_downsample_filter.param.yaml
      dest: tier4_localization_launch/config/random_downsample_filter.param.yaml
    - source: launch/tier4_localization_launch/config/crop_box_filter_measurement_range.param.yaml
      dest: tier4_localization_launch/config/crop_box_filter_measurement_range.param.yaml
    - source: launch/tier4_system_launch/config/system_monitor/cpu_monitor.param.yaml
      dest: tier4_system_launch/config/system_monitor/cpu_monitor.param.yaml
    - source: launch/tier4_system_launch/config/system_monitor/hdd_monitor.param.yaml
      dest: tier4_system_launch/config/system_monitor/hdd_monitor.param.yaml
    - source: launch/tier4_system_launch/config/system_monitor/ntp_monitor.param.yaml
      dest: tier4_system_launch/config/system_monitor/ntp_monitor.param.yaml
    - source: launch/tier4_system_launch/config/system_monitor/net_monitor.param.yaml
      dest: tier4_system_launch/config/system_monitor/net_monitor.param.yaml
    - source: launch/tier4_system_launch/config/system_monitor/process_monitor.param.yaml
      dest: tier4_system_launch/config/system_monitor/process_monitor.param.yaml
    - source: launch/tier4_system_launch/config/system_monitor/mem_monitor.param.yaml
      dest: tier4_system_launch/config/system_monitor/mem_monitor.param.yaml
    - source: launch/tier4_system_launch/config/system_monitor/gpu_monitor.param.yaml
      dest: tier4_system_launch/config/system_monitor/gpu_monitor.param.yaml
    - source: launch/tier4_system_launch/config/diagnostic_aggregator/vehicle.param.yaml
      dest: tier4_system_launch/config/diagnostic_aggregator/vehicle.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/common/common.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/common/common.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/L2.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/L2.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/Linf.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/Linf.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/JerkFiltered.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/JerkFiltered.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/Analytical.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/Analytical.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/adaptive_cruise_control.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/adaptive_cruise_control.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/occlusion_spot.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/occlusion_spot.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/blind_spot.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/blind_spot.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/stop_line.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/stop_line.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/traffic_light.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/traffic_light.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/no_stopping_area.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/no_stopping_area.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_traffic_light.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_traffic_light.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/detection_area.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/detection_area.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_out/pull_out.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_out/pull_out.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/side_shift/side_shift.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/side_shift/side_shift.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_following/lane_following.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_following/lane_following.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/lane_change_planner/lane_change_planner.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/lane_change_planner/lane_change_planner.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/rtc_auto_approver/rtc_auto_approver.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/rtc_auto_approver/rtc_auto_approver.param.yaml
    - source: launch/tier4_planning_launch/config/scenario_planning/parking/freespace_planner/freespace_planner.param.yaml
      dest: tier4_planning_launch/config/scenario_planning/parking/freespace_planner/freespace_planner.param.yaml
    - source: launch/tier4_control_launch/config/trajectory_follower/longitudinal_controller.param.yaml
      dest: tier4_control_launch/config/trajectory_follower/longitudinal_controller.param.yaml
    - source: launch/tier4_control_launch/config/trajectory_follower/lateral_controller.param.yaml
      dest: tier4_control_launch/config/trajectory_follower/lateral_controller.param.yaml
    - source: launch/tier4_control_launch/config/trajectory_follower/latlon_muxer.param.yaml
      dest: tier4_control_launch/config/trajectory_follower/latlon_muxer.param.yaml
    - source: launch/tier4_control_launch/config/operation_mode_transition_manager/operation_mode_transition_manager.param.yaml
      dest: tier4_control_launch/config/operation_mode_transition_manager/operation_mode_transition_manager.param.yaml
    - source: launch/tier4_control_launch/config/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
      dest: tier4_control_launch/config/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
