tier4/autoware_launch:
  default-upstream-id: awf
  upstreams:
    awf: # upstream ID
      name: AWF
      url: https://github.com/autowarefoundation/autoware_launch.git
      syncs:
        - upstream: main
          base: tier4/main
          reviewers: # use actual GitHub users or teams
            - rej55

tier4/autoware_launch.x2:
  default-upstream-id: vanilla
  upstreams:
    vanilla: # upstream ID
      name: vanilla
      url: https://github.com/tier4/autoware_launch.git
      syncs:
        - upstream: stable
          base: tier4/main
          reviewers:
            - TomohitoAndo
        - upstream: beta/v0.48
          base: beta/v4.3
          reviewers:
            - TomohitoAndo
        - upstream: beta/v0.64
          base: beta/v4.4
          reviewers:
            - TomohitoAndo
            - paulsohn
