/**:
  ros__parameters:
    diagnostics:
      functional_safety:
        mode: advanced
        error_definitions_path: $(find-pkg-share autoware_launch)/config/sensing/lidar/diagnostics/qt128_fusa_codes.csv
        # In ROS 2, parameters cannot be an empty list, so this is commented out.
        # ignored_error_codes:
        #  - 0xaaaa # justification
