# This file is managed by sync-params workflow.
# Keys marked with '{OVERRIDE}' or '# {OVERRIDE: reason}' are persisted as variant overrides.
# 'reason' can be any single-line text without braces.
# To keep local changes, annotate fields with '# {OVERRIDE}' or '# {OVERRIDE: reason}'.
#
# Source: https://github.com/autowarefoundation/autoware_universe/blob/de9fc094b7eaaf40b40f27bf1b694166c048cd69/localization/autoware_pose_instability_detector/config/pose_instability_detector.param.yaml

/**:
  ros__parameters:
    timer_period: 0.5                             # [sec]

    heading_velocity_maximum: 16.667              # [m/s]
    heading_velocity_scale_factor_tolerance: 3.0  # [%]

    angular_velocity_maximum: 0.523               # [rad/s]
    angular_velocity_scale_factor_tolerance: 0.2  # [%]
    angular_velocity_bias_tolerance: 0.00698      # [rad/s]

    pose_estimator_longitudinal_tolerance: 0.11   # [m]
    pose_estimator_lateral_tolerance: 0.11        # [m]
    pose_estimator_vertical_tolerance: 0.5        # [m]
    pose_estimator_angular_tolerance: 0.0175      # [rad]

    enable_validation:
      position_x: true
      position_y: true
      position_z: true
      angle_x: false
      angle_y: false
      angle_z: true
