/**:
  ros__parameters:
    update_interval: 0.1
    initial_speed_scale_factor: 1.0
    initial_speed_scale_factor_covariance: 1000.0
    process_noise_covariance: 0.01
    measurement_noise_covariance: 0.01
    max_angular_velocity: 0.0105 # [rad/s] 0.6 [deg/s]
    max_speed: 17.0 # [m/s]
    min_speed: 6.0 # [m/s]
