/**:
  ros__parameters:
    tolerance_m: 0.7
    voxel_leaf_size_m: 0.3
    min_points_per_voxel: 1
    min_points_per_cluster: 10
    max_voxels_per_cluster: 800
    large_cluster_voxel_count_threshold: 65
    large_cluster_max_points_per_voxel: 10
    use_height: false
    input_frame: "base_link"

    # low height crop box filter param
    max_x: 200.0
    min_x: -200.0
    max_y: 200.0
    min_y: -200.0
    max_z: 4.0
    min_z: -10.0
    negative: false
    processing_time_threshold_sec: 0.01
