/**:
  ros__parameters:
    debug_mode: true # Whether to enable debug mode, which may include additional logging
    max_camera_time_diff: 0.15 #Maximum allowed time difference for camera image sync in seconds
    multithreading: false # Whether to use multithreading for handling image callbacks
    anchor_camera_id: 0 # Camera id of the anchor topic. The forward pass begins once every anchor camera topic reaches.
    is_compressed_image: false # Whether the input images are compressed
    is_distorted_image: false # Whether the input images are distorted
