/**:
  ros__parameters:
    approximate_sync: false
    label_path: $(var data_path)/traffic_light_classifier/lamp_labels.txt
    precision: fp16
    mean: [123.675, 116.28, 103.53] # It depends on the data on which ML model is trained
    std: [58.395, 57.12, 57.375] # It depends on the data on which ML model is trained
    over_exposure_threshold: 0.85
    under_exposure_threshold: -0.83
    classifier_type: 1 # classifier_type { hsv_filter: 0, cnn: 1 }
    traffic_light_type: 0 # classify_traffic_light_type { car: 0, pedestrian: 1 }
