/**:
  ros__parameters:
    approximate_sync: false
    label_path: /opt/autoware/mlmodels/traffic_light_classifier/lamp_labels_ped.txt
    model_path: /opt/autoware/mlmodels/traffic_light_classifier/ped_traffic_light_classifier_mobilenetv2_batch_6.onnx
    precision: fp16
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.12, 57.375]
    over_exposure_threshold: 0.85
    under_exposure_threshold: -0.83
    classifier_type: 1 # classifier_type { hsv_filter: 0, cnn: 1 }
    traffic_light_type: 1 # classify_traffic_light_type { car: 0, pedestrian: 1 }
