/**:
  ros__parameters:
    min_ok_rate: 9.0
    min_warn_rate: 8.0
    observed_frames_transition: 10
    immediate_error_report: false
    immediate_relax_state: false
    diag_publish_rate: 10.0 # This value is expected to be aligned to the ideal camera frame rate
