/**:
  ros__parameters:
    fine_detector_label_path: "/opt/autoware/tlr_labels.txt"
    fine_detector_model_path: "/opt/autoware/tlr_car_ped_yolox_s_batch_6.onnx"
    fine_detector_precision: fp16
    fine_detector_score_thresh: 0.3
    fine_detector_nms_thresh: 0.65
    approximate_sync: false
    gpu_id: 0
