uevent_description:
  hardware_type: "proframe_camera"
  devpath: "/dev/sxpf0"
  identifier_key: "CAUSE1"
  key_is: "0"
  hardware_id: "camera8"
  value_key: "FUSA_HW_FAULT"
  value_type: "error_flag"
  criteria:
    status_ok: 1
    status_error: 0
uevent_description:
  hardware_type: "proframe_camera"
  devpath: "/dev/sxpf0"
  identifier_key: "CAUSE1"
  key_is: "2"
  hardware_id: "camera9"
  value_key: "FUSA_HW_FAULT"
  value_type: "error_flag"
  criteria:
    status_ok: 1
    status_error: 0
uevent_description:
  hardware_type: "proframe_camera"
  devpath: "/dev/sxpf0"
  identifier_key: "CAUSE1"
  key_is: "4"
  hardware_id: "camera10"
  value_key: "FUSA_HW_FAULT"
  value_type: "error_flag"
  criteria:
    status_ok: 1
    status_error: 0
