<?xml version="1.0"?>
<package format="3">
  <name>autoware_launch</name>
  <version>0.50.0</version>
  <description>The autoware_launch package</description>

  <maintainer email="yukihiro.saito@tier4.jp">Yukihiro Saito</maintainer>
  <maintainer email="ryohsuke.mitsudome@tier4.jp">Ryohsuke Mitsudome</maintainer>
  <maintainer email="mfc@leodrive.ai">M. Fatih Cırıt</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <exec_depend>aip_x2_gen2_launch</exec_depend>
  <exec_depend>autoware_adapi_adaptors</exec_depend>
  <exec_depend>autoware_agnocast_wrapper</exec_depend>
  <exec_depend>autoware_behavior_path_direction_change_module</exec_depend>
  <exec_depend>autoware_carla_interface</exec_depend>
  <exec_depend>autoware_command_mode_decider</exec_depend>
  <exec_depend>autoware_command_mode_switcher</exec_depend>
  <exec_depend>autoware_control_command_gate</exec_depend>
  <exec_depend>autoware_diagnostic_graph_aggregator</exec_depend>
  <exec_depend>autoware_diagnostic_graph_utils</exec_depend>
  <exec_depend>autoware_diagnostic_status_auto_reset_manager</exec_depend>
  <exec_depend>autoware_diffusion_planner</exec_depend>
  <exec_depend>autoware_mppi_optimizer</exec_depend>
  <exec_depend>autoware_trajectory_processor</exec_depend>
  <exec_depend>autoware_dummy_diag_publisher</exec_depend>
  <exec_depend>autoware_dummy_infrastructure</exec_depend>
  <exec_depend>autoware_ekf_localizer</exec_depend>
  <exec_depend>autoware_ekf_localizer_auto_activator</exec_depend>
  <exec_depend>autoware_global_parameter_loader</exec_depend>
  <exec_depend>autoware_hazard_lights_selector</exec_depend>
  <exec_depend>autoware_in_lane_mrm_planner</exec_depend>
  <exec_depend>autoware_minimum_rule_based_planner</exec_depend>
  <exec_depend>autoware_operation_mode_service_caller</exec_depend>
  <exec_depend>autoware_operation_mode_service_divider</exec_depend>
  <exec_depend>autoware_planning_evaluator</exec_depend>
  <exec_depend>autoware_planning_validator</exec_depend>
  <exec_depend>autoware_proximity_hazard_checker</exec_depend>
  <exec_depend>autoware_raw_vehicle_cmd_converter</exec_depend>
  <exec_depend>autoware_redundancy_relay_manager</exec_depend>
  <exec_depend>autoware_remaining_distance_time_calculator</exec_depend>
  <exec_depend>autoware_reset_service_caller</exec_depend>
  <exec_depend>autoware_reset_service_divider</exec_depend>
  <exec_depend>autoware_speed_scale_estimator</exec_depend>
  <exec_depend>autoware_stop_filter</exec_depend>
  <exec_depend>autoware_topic_relay_controller</exec_depend>
  <exec_depend>autoware_topic_state_monitor</exec_depend>
  <exec_depend>autoware_trajectory_adapter</exec_depend>
  <exec_depend>autoware_trajectory_dummy_gate</exec_depend>
  <exec_depend>autoware_trajectory_processor</exec_depend>
  <exec_depend>autoware_trajectory_ranker</exec_depend>
  <exec_depend>autoware_trajectory_selector</exec_depend>
  <exec_depend>autoware_twist2accel</exec_depend>
  <exec_depend>autoware_vehicle_velocity_converter</exec_depend>
  <exec_depend>control_cmd_switcher</exec_depend>
  <exec_depend>daytime_monitor</exec_depend>
  <exec_depend>default_adapi_custom_launch</exec_depend>
  <exec_depend>diagnostic_graph_merger</exec_depend>
  <exec_depend>diagnostic_latch_canceler</exec_depend>
  <exec_depend>domain_bridge</exec_depend>
  <exec_depend>individual_params</exec_depend>
  <exec_depend>j6_can_interface</exec_depend>
  <exec_depend>j6_gen2_launch</exec_depend>
  <exec_depend>j6_interface</exec_depend>
  <exec_depend>jerk_constant_deceleration_controller</exec_depend>
  <exec_depend>l4_toolkit_launch</exec_depend>
  <exec_depend>max_speed_selector</exec_depend>
  <exec_depend>mrm_diagnostic_overrider</exec_depend>
  <exec_depend>output_master_manager</exec_depend>
  <exec_depend>python3-bson</exec_depend>
  <exec_depend>python3-tornado</exec_depend>
  <exec_depend>redundancy_switcher_interface</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>tier4_autoware_api_extension_launch</exec_depend>
  <exec_depend>tier4_autoware_api_launch</exec_depend>
  <exec_depend>tier4_control_launch</exec_depend>
  <exec_depend>tier4_localization_launch</exec_depend>
  <exec_depend>tier4_map_launch</exec_depend>
  <exec_depend>tier4_perception_launch</exec_depend>
  <exec_depend>tier4_planning_launch</exec_depend>
  <exec_depend>tier4_sensing_launch</exec_depend>
  <exec_depend>tier4_simulator_launch</exec_depend>
  <exec_depend>tier4_system_launch</exec_depend>
  <exec_depend>tier4_vehicle_launch</exec_depend>
  <exec_depend>traffic_signal_launcher</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>autoware_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <autoware_guideline_check file="test/autoware_guideline_check.yaml"/>
  </export>
</package>
