/**:
  ros__parameters:
    bidirectional_traffic:
      forward_looking_distance: 100.0
      keep_left_ratio: 0.2
      pull_over_ratio: 0.7
      time_to_prepare_pull_over: 1.0
      default_shift_distance_to_pull_over: 10.0
      max_curvature_increase: 10.0
