# This file is managed by workflow.
# Keys marked with '*OVERRIDE*' are persisted as variant overrides.
# If you want to modify a field, make sure that the field has comment including -> # *OVERRIDE*
#
# Source: https://github.com/autowarefoundation/autoware_universe/blob/56592b79e04262a328ae5e393675c1271e045635/perception/autoware_image_projection_based_fusion/config/pointpainting_common.param.yaml

/**:
  ros__parameters:
    diagnostics:
      # When the processing time exceeds the max_allowed_processing_time,
      # a warning will be triggered.
      max_allowed_processing_time_ms: 200.0 # in milliseconds
      # If the warning is triggered and if a timestamp of last normal processing is more than
      # max_acceptable_consecutive_delay_ms, an error diagnostic message will be sent.
      max_acceptable_consecutive_delay_ms: 1000.0
      # interval of diagnostic callback in milliseconds
      pointpainting_validation_callback_interval_ms: 100.0 # in milliseconds

# ###### ORIGINAL (DO NOT EDIT) ######
# /**:
#   ros__parameters:
#     diagnostics:
#       # When the processing time exceeds the max_allowed_processing_time,
#       # a warning will be triggered.
#       max_allowed_processing_time_ms: 200.0 # in milliseconds
#       # If the warning is triggered and if a timestamp of last normal processing is more than
#       # max_acceptable_consecutive_delay_ms, an error diagnostic message will be sent.
#       max_acceptable_consecutive_delay_ms: 1000.0
#       # interval of diagnostic callback in milliseconds
#       pointpainting_validation_callback_interval_ms: 100.0 # in milliseconds
