/**:
  ros__parameters:
    fuse_unknown_only: true
    min_cluster_size: 2
    max_cluster_size: 20
    cluster_2d_tolerance: 0.5
    roi_scale_factor: 1.0
    max_object_size: 2.0
    override_class_with_unknown: false
    fusion_enabled_classes:
      UNKNOWN: true
      CAR: false
      BUS: false
      TRUCK: false
      TRAILER: false
      MOTORCYCLE: false
      BICYCLE: true
      PEDESTRIAN: true
      ANIMAL: true
      HAZARD: true
