files:
  - { path: $(dirname)/control.yaml }
  - { path: $(dirname)/localization.yaml }
  - { path: $(dirname)/map.yaml }
  - { path: $(dirname)/perception.yaml }
  - { path: $(dirname)/planning.yaml }
  - { path: $(dirname)/system.yaml }
  - { path: $(dirname)/vehicle.yaml }

units:
  - path: /autoware/modes/local
    type: and
    list:
      - { type: link, link: /autoware/vehicle }
      - { type: link, link: /autoware/system }
      - { type: link, link: /autoware/control/local }
      - { type: link, link: /adapi/mrm_request/delegate }

  - path: /autoware/modes/remote
    type: and
    list:
      - { type: link, link: /autoware/vehicle }
      - { type: link, link: /autoware/system }
      - { type: link, link: /autoware/control/remote }
      - { type: link, link: /adapi/mrm_request/delegate }

  - path: /autoware/modes/stop
    type: and
    list:
      - { type: link, link: /adapi/mrm_request/delegate }

  - path: /autoware/modes/autonomous
    type: and
    list:
      - { type: link, link: /autoware/map }
      - { type: link, link: /autoware/localization }
      - { type: link, link: /autoware/planning }
      - { type: link, link: /autoware/perception }
      - { type: link, link: /autoware/control }
      - { type: link, link: /autoware/vehicle }
      - { type: link, link: /autoware/system }
      - { type: link, link: /adapi/mrm_request/delegate }

  - path: /autoware/modes/pull_over
    type: and
    list:
      - { type: link, link: /autoware/map }
      - { type: link, link: /autoware/localization }
      - { type: link, link: /autoware/planning }
      - { type: link, link: /autoware/perception }
      - { type: link, link: /autoware/control }
      - { type: link, link: /autoware/vehicle }
      - { type: link, link: /autoware/system }

  - path: /autoware/modes/comfortable_stop
    type: and
    list:
      - { type: link, link: /autoware/map }
      - { type: link, link: /autoware/localization }
      - { type: link, link: /autoware/planning }
      - { type: link, link: /autoware/perception }
      - { type: link, link: /autoware/control }
      - { type: link, link: /autoware/vehicle }
      - { type: link, link: /autoware/system }

  - path: /autoware/modes/emergency_stop
    type: and
    list:
      - { type: link, link: /autoware/vehicle }
      - { type: link, link: /autoware/system }

  - path: /autoware/debug/tools
    type: and
    list:
      - { type: link, link: /autoware/system/service_log_checker }

  - path: /adapi/mrm_request/delegate
    type: diag
    node: /adapi/node/mrm_request
    name: delegate
