files:
  - { path: $(dirname)/autoware-main-base.yaml }

units:
  - path: /planning/dp_comfortable_stop_blocked
    type: error

  - path: /autoware/modes/comfortable_stop
    type: and
    list:
      - { type: link, link: /control/comfortable_stop_available }
      - { type: link, link: /foolproof/comfortable_stop_available }
      - { type: link, link: /hardware/comfortable_stop_available }
      - { type: link, link: /localization/comfortable_stop_available }
      - { type: link, link: /map/comfortable_stop_available }
      - { type: link, link: /perception/comfortable_stop_available }
      - { type: link, link: /planning/comfortable_stop_available }
      - { type: link, link: /sensing/comfortable_stop_available }
      - { type: link, link: /system/comfortable_stop_available }
      - { type: link, link: /vehicle/comfortable_stop_available }
      - { type: link, link: /planning/dp_comfortable_stop_blocked }

edits:
  - { type: remove, path: /system/018-emergency_vehicle_main-error }
  - { type: remove, path: /control/010-collision_detector-error }
