units:
  - path: /control/autonomous_available
    type: and
    list:
      - { type: link, link: /control/emergency_stop }
      - { type: link, link: /control/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /control/in_lane_emergency_stop }
      - { type: link, link: /control/in_lane_moderate_stop }
      - { type: link, link: /control/comfortable_stop }

  - path: /control/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /control/emergency_stop }
      - { type: link, link: /control/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /control/in_lane_emergency_stop }
      - { type: link, link: /control/in_lane_moderate_stop }

  - path: /control/in_lane_moderate_stop_available
    type: and
    list:
      - { type: link, link: /control/emergency_stop }
      - { type: link, link: /control/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /control/in_lane_emergency_stop }

  - path: /control/in_lane_emergency_stop_available
    type: and
    list:
      - { type: link, link: /control/emergency_stop }
      - { type: link, link: /control/sub_ecu_in_lane_moderate_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /control/emergency_stop
    type: and

  - path: /control/sub_ecu_in_lane_moderate_stop
    type: and
    list:
      - { type: link, link: /control/control_command_gate/timeout_in_lane_stop-error }
      - { type: link, link: /control/control_command_gate/timeout_output-error }

  - path: /control/in_lane_emergency_stop
    type: and
    list:
      - { type: link, link: /control/006-boundary_departure-error }
      - { type: link, link: /control/007-aeb_emergency_stop-error }
      - { type: link, link: /control/011-rolling_back-error }
      - { type: link, link: /control/012-overrun_stop_point-error }
      - { type: link, link: /control/011-rolling_back-error }

  - path: /control/in_lane_moderate_stop
    type: and
    list:
      - { type: link, link: /control/002-topic_status/control_command-error }
      - { type: link, link: /control/003-max_distance_deviation-error }
      - { type: link, link: /control/004-over_velocity-error }
      - { type: link, link: /control/009-slip_detection-error }
      - { type: link, link: /control/control_command_gate/timeout_main-error }

  - path: /control/comfortable_stop
    type: and
    list:
      - { type: link, link: /control/005-yaw_deviation-error }
      - { type: link, link: /control/control_command_gate/timeout_stop-error }
      - { type: link, link: /control/010-collision_detector-error }

  - path: /control/none
    type: and
    list:
      - { type: link, link: /control/013-will_overrun_stop_point-error }
      - { type: link, link: /control/014-acceleration_error-error }
      - { type: link, link: /control/016-sudden_deceleration_monitor-error }

  # Intermediate paths
  - path: /control/002-topic_status/control_command-error
    type: warn-to-ok
    item:
      type: link
      link: /control/002-topic_status/control_command

  - path: /control/003-max_distance_deviation-error
    type: warn-to-ok
    item:
      type: link
      link: /control/003-max_distance_deviation

  - path: /control/004-over_velocity-error
    type: warn-to-ok
    item:
      type: link
      link: /control/004-over_velocity

  - path: /control/control_command_gate/timeout_stop-error
    type: warn-to-ok
    item:
      type: link
      link: /control/control_command_gate/timeout_stop

  - path: /control/control_command_gate/timeout_main-error
    type: warn-to-ok
    item:
      type: link
      link: /control/control_command_gate/timeout_main

  - path: /control/control_command_gate/timeout_in_lane_stop-error
    type: warn-to-ok
    item:
      type: link
      link: /control/control_command_gate/timeout_in_lane_stop

  - path: /control/control_command_gate/timeout_output-error
    type: warn-to-ok
    item:
      type: link
      link: /control/control_command_gate/timeout_output

  - path: /control/005-yaw_deviation-error
    type: warn-to-ok
    item:
      type: link
      link: /control/005-yaw_deviation

  - path: /control/006-boundary_departure-error
    type: warn-to-ok
    item:
      type: link
      link: /control/006-boundary_departure

  - path: /control/007-aeb_emergency_stop-error
    type: warn-to-ok
    item:
      type: link
      link: /control/007-aeb_emergency_stop

  - path: /control/009-slip_detection-error
    type: warn-to-ok
    item:
      type: link
      link: /control/009-slip_detection

  - path: /control/010-collision_detector-error
    type: warn-to-ok
    item:
      type: link
      link: /control/010-collision_detector

  - path: /control/011-rolling_back-error
    type: warn-to-ok
    item:
      type: link
      link: /control/011-rolling_back

  - path: /control/012-overrun_stop_point-error
    type: warn-to-ok
    item:
      type: link
      link: /control/012-overrun_stop_point

  - path: /control/013-will_overrun_stop_point-error
    type: warn-to-ok
    item:
      type: link
      link: /control/013-will_overrun_stop_point

  - path: /control/014-acceleration_error-error
    type: warn-to-ok
    item:
      type: link
      link: /control/014-acceleration_error

  - path: /control/016-sudden_deceleration_monitor-error
    type: warn-to-ok
    item:
      type: link
      link: /control/016-sudden_deceleration_monitor

  - path: /control/002-topic_status/control_command
    type: diag
    node: topic_state_monitor_control_command_control_cmd
    name: control_topic_status
    timeout: 1.0
    latch: 0.0

  - path: /control/003-max_distance_deviation
    type: diag
    node: control_validator
    name: control_validation_max_distance_deviation
    timeout: 1.0
    latch: 0.0

  - path: /control/004-over_velocity
    type: diag
    node: control_validator
    name: control_validation_over_velocity
    timeout: 1.0
    latch: 0.0

  - path: /control/005-yaw_deviation
    type: diag
    node: control_validator
    name: control_validation_yaw_deviation
    timeout: 1.0
    latch: 0.0

  - path: /control/006-boundary_departure
    type: diag
    node: motion_velocity_planner
    name: boundary_departure
    timeout: 1.0
    latch: 0.0

  - path: /control/007-aeb_emergency_stop
    type: diag
    node: autonomous_emergency_braking
    name: aeb_emergency_stop
    timeout: 1.0
    latch: 0.0

  - path: /control/009-slip_detection
    type: diag
    node: slip_detector
    name: slip_status
    timeout: 3.0
    latch: 0.0

  - path: /control/010-collision_detector
    type: diag
    node: collision_detector
    name: collision_detect
    timeout: 1.0
    latch: 0.0

  - path: /control/011-rolling_back
    type: diag
    node: control_validator
    name: control_validation_rolling_back
    timeout: 1.0
    latch: 0.0

  - path: /control/012-overrun_stop_point
    type: diag
    node: control_validator
    name: control_validation_overrun_stop_point
    timeout: 1.0
    latch: 0.0

  - path: /control/013-will_overrun_stop_point
    type: diag
    node: control_validator
    name: control_validation_will_overrun_stop_point
    timeout: 1.0
    latch: 0.0

  - path: /control/014-acceleration_error
    type: diag
    node: control_validator
    name: control_validation_acceleration_error
    timeout: 1.0
    latch: 0.0

  - path: /control/control_command_gate/timeout_stop
    type: diag
    node: control_command_gate
    name: timeout_stop
    timeout: 1.0
    latch: 0.0

  - path: /control/control_command_gate/timeout_main
    type: diag
    node: control_command_gate
    name: timeout_main
    timeout: 1.0
    latch: 0.0

  - path: /control/control_command_gate/timeout_in_lane_stop
    type: diag
    node: control_command_gate
    name: timeout_in_lane_stop
    timeout: 1.0
    latch: 0.0

  - path: /control/control_command_gate/timeout_output
    type: diag
    node: control_command_gate
    name: timeout_output
    timeout: 1.0
    latch: 0.0
  - path: /control/016-sudden_deceleration_monitor
    type: diag
    node: sudden_deceleration_monitor
    name: sudden_deceleration_monitor
    timeout: 1.0
    latch: 0.0
