# Description:
#   required_diags:
#     <name>: {is_active: <is_active>, status: <status>}
#   name: diag name
#   is_active: Force update or not
#   status: diag status set by dummy diag publisher "OK, Warn, Error, Stale"
#
# Note:
#
# default values are:
#   is_active: "true"
#   status: "OK"
---
/**:
  ros__parameters:
    required_diags:
      # hardware

      ## /sub_ecu/hardware/cpu/001-temperature
      "cpu_monitor_sub: CPU Temperature": default

      ## /sub_ecu/hardware/cpu/002-usage
      "cpu_monitor_sub: CPU Usage": default

      ## /sub_ecu/hardware/cpu/003-load_average
      "cpu_monitor_sub: CPU Load Average": default

      ## /sub_ecu/hardware/cpu/004-throttling
      "cpu_monitor_sub: CPU Thermal Throttling": default

      ## /sub_ecu/hardware/cpu/005-frequency
      "cpu_monitor_sub: CPU Frequency": default

      ## /sub_ecu/hardware/hdd/001-temperature
      "hdd_monitor_sub: HDD Temperature": default

      ## /sub_ecu/hardware/hdd/002-usage
      "hdd_monitor_sub: HDD Usage": default

      ## /sub_ecu/hardware/hdd/003-connection
      "hdd_monitor_sub: HDD Connection": default

      ## /sub_ecu/hardware/hdd/004-total_written
      "hdd_monitor_sub: HDD TotalDataWritten": default

      ## /sub_ecu/hardware/hdd/005-warranty_period
      "hdd_monitor_sub: HDD PowerOnHours": default

      ## /sub_ecu/hardware/hdd/006-soft_error
      "hdd_monitor_sub: HDD RecoveredError": default

      ## /sub_ecu/hardware/hdd/007-load
      "hdd_monitor_sub: HDD ReadDataRate": default
      "hdd_monitor_sub: HDD WriteDataRate": default
      "hdd_monitor_sub: HDD ReadIOPS": default
      "hdd_monitor_sub: HDD WriteIOPS": default

      ## /sub_ecu/hardware/memory/001-usage
      "mem_monitor_sub: Memory Usage": default

      ## /sub_ecu/hardware/memory/002-ecc
      "mem_monitor_sub: Memory ECC": default

      ## /sub_ecu/hardware/network/001-usage
      "net_monitor_sub: Network Usage": default

      ## /sub_ecu/hardware/network/002-traffic
      "net_monitor_sub: Network Traffic": default

      ## /sub_ecu/hardware/network/003-crc
      "net_monitor_sub: Network CRC Error": default

      ## /sub_ecu/hardware/network/004-packet_reassembles
      "net_monitor_sub: IP Packet Reassembles Failed": default

      ## /sub_ecu/hardware/gpu/001-temperature
      "gpu_monitor_sub: GPU Temperature": default

      ## /sub_ecu/hardware/gpu/002-usage
      "gpu_monitor_sub: GPU Usage": default

      ## /sub_ecu/hardware/gpu/003-memory
      "gpu_monitor_sub: GPU Memory Usage": default

      ## /sub_ecu/hardware/gpu/004-throttling
      "gpu_monitor_sub: GPU Thermal Throttling": default

      ## /sub_ecu/hardware/gpu/005-frequency
      "gpu_monitor_sub: GPU Frequency": default

      ## /sub_ecu/localization/topic_status/pose
      "topic_state_monitor_pose_with_covariance: topic_status": default

      ## /sub_ecu/localization/topic_status/twist
      "topic_state_monitor_twist_with_covariance: topic_status": default

      ##/sub_ecu/sensing/imu/gyro_bias_validation
      "gyro_bias_scale_validator: gyro_bias_scale_validator": default

      ##/sub_ecu/sensing/imu/rate_bound_check
      "/sensing/imu/tamagawa/tag_can_driver: rate bound check": default

      ## /sub_ecu/vehicle/topic_status/actuation_command
      "topic_state_monitor_control_command_actuation_cmd: topic_status": default

      ## /sub_ecu/vehicle/topic_status/velocity
      "topic_state_monitor_vehicle_status_velocity_status: topic_status": default

      ## /sub_ecu/vehicle/topic_status/steering
      "topic_state_monitor_vehicle_status_steering_status: topic_status": default

      ## /sub_ecu/vehicle/vcu_not_authenticated
      "j6_interface: vcu_not_authenticated": default

      ## /sub_ecu/vehicle/t4_vcu_version_check
      "j6_interface: t4-vcu_version_check": default

      ## /sub_ecu/foolproof/sub/autoware_node_alive
      "autoware_diagnostics_bridge_node_sub: sub_autoware_node_alive": default
