units:
  - path: /foolproof/autonomous_available
    type: and
    list:
      - { type: link, link: /foolproof/emergency_stop }
      - { type: link, link: /foolproof/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /foolproof/in_lane_emergency_stop }
      - { type: link, link: /foolproof/in_lane_moderate_stop }
      - { type: link, link: /foolproof/comfortable_stop }

  - path: /foolproof/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /foolproof/emergency_stop }
      - { type: link, link: /foolproof/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /foolproof/in_lane_emergency_stop }
      - { type: link, link: /foolproof/in_lane_moderate_stop }

  - path: /foolproof/in_lane_moderate_stop_available
    type: and
    list:
      - { type: link, link: /foolproof/emergency_stop }
      - { type: link, link: /foolproof/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /foolproof/in_lane_emergency_stop }

  - path: /foolproof/in_lane_emergency_stop_available
    type: and
    list:
      - { type: link, link: /foolproof/emergency_stop }
      - { type: link, link: /foolproof/sub_ecu_in_lane_moderate_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /foolproof/emergency_stop
    type: and
    # list:
    # - { type: link, link:  /foolproof/device_check }

  - path: /foolproof/comfortable_stop
    type: and
    list:
      - { type: link, link: /foolproof/main/update_status_ota }
      - { type: link, link: /foolproof/main/update_status_map }
      - { type: link, link: /foolproof/main/update_status_unrecoverable }

  - path: /foolproof/in_lane_emergency_stop
    type: and
    # list:

  - path: /foolproof/in_lane_moderate_stop
    type: and
    list:
      - { type: link, link: /foolproof/logging/heartbeat }
      - { type: link, link: /foolproof/perception1/heartbeat }
      - { type: link, link: /foolproof/perception2/heartbeat }
      - { type: link, link: /foolproof/logging/ssd_not_found-error }
      - { type: link, link: /foolproof/perception1/camera_not_found-error }
      - { type: link, link: /foolproof/perception2/camera_not_found-error }
      - { type: link, link: /foolproof/perception1/mgbe1_not_ready-error }
      - { type: link, link: /foolproof/perception2/mgbe1_not_ready-error }
      - { type: link, link: /foolproof/addon/heartbeat }

  - path: /foolproof/sub_ecu_in_lane_moderate_stop
    type: and
    list:
      - { type: link, link: /foolproof/main/scheduling_settings_others }
      - { type: link, link: /foolproof/main/scheduling_settings_autoware }
      - { type: link, link: /foolproof/main/autoware_node_alive }
      - { type: link, link: /foolproof/main/autoware_system_node_alive }
      - { type: link, link: /foolproof/perception1/recognition_node_alive }
      - { type: link, link: /foolproof/perception2/recognition_node_alive }
      - { type: link, link: /foolproof/addon/recognition_node_alive }
      - { type: link, link: /foolproof/addon/camera_driver_node_alive }

  - path: /foolproof/none
    type: and
    # list:

  # *******************************************************************************
  # warning makes it ok
  # *******************************************************************************

  - path: /foolproof/logging/ssd_not_found-error
    type: warn-to-ok
    item:
      type: link
      link: /foolproof/logging/ssd_not_found

  - path: /foolproof/perception1/camera_not_found-error
    type: warn-to-ok
    item:
      type: link
      link: /foolproof/perception1/camera_not_found

  - path: /foolproof/perception2/camera_not_found-error
    type: warn-to-ok
    item:
      type: link
      link: /foolproof/perception2/camera_not_found

  - path: /foolproof/perception1/mgbe1_not_ready-error
    type: warn-to-ok
    item:
      type: link
      link: /foolproof/perception1/mgbe1_not_ready

  - path: /foolproof/perception2/mgbe1_not_ready-error
    type: warn-to-ok
    item:
      type: link
      link: /foolproof/perception2/mgbe1_not_ready

  # *******************************************************************************
  # Set path, node to identify and name for each individual error.
  # *******************************************************************************
  # Heartbeat
  - path: /foolproof/logging/heartbeat
    type: diag
    node: autoware_diagnostics_bridge_node_logging
    name: heartbeat
    timeout: 3.0
    # latch: 0.0

  - path: /foolproof/perception1/heartbeat
    type: diag
    node: autoware_diagnostics_bridge_node_perception1
    name: heartbeat
    timeout: 3.0
    # latch: 0.0

  - path: /foolproof/perception2/heartbeat
    type: diag
    node: autoware_diagnostics_bridge_node_perception2
    name: heartbeat
    timeout: 3.0
    # latch: 0.0

  - path: /foolproof/addon/heartbeat
    type: diag
    node: autoware_diagnostics_bridge_node_addon
    name: heartbeat
    timeout: 3.0
    # latch: 0.0

  # fool proof check
  - path: /foolproof/logging/ssd_not_found
    type: diag
    node: autoware_diagnostics_bridge_node_logging
    name: logging_ssd
    timeout: 10.0
    # latch: 0.0

  - path: /foolproof/perception1/camera_not_found
    type: diag
    node: autoware_diagnostics_bridge_node_perception1
    name: perception1_camera
    timeout: 10.0
    # latch: 0.0

  - path: /foolproof/perception2/camera_not_found
    type: diag
    node: autoware_diagnostics_bridge_node_perception2
    name: perception2_camera
    timeout: 10.0
    # latch: 0.0

  - path: /foolproof/perception1/mgbe1_not_ready
    type: diag
    node: autoware_diagnostics_bridge_node_perception1
    name: perception1_mgbe1-ready
    timeout: 10.0
    # latch: 0.0

  - path: /foolproof/perception2/mgbe1_not_ready
    type: diag
    node: autoware_diagnostics_bridge_node_perception2
    name: perception2_mgbe1-ready
    timeout: 10.0
    # latch: 0.0

  # letterbox_monitor
  - path: /foolproof/main/autoware_node_alive
    type: diag
    node: autoware_diagnostics_bridge_node_main
    name: main_autoware_node_alive
    timeout: 3.0
    # latch: 0.0

  - path: /foolproof/main/autoware_system_node_alive
    type: diag
    node: autoware_diagnostics_bridge_node_main
    name: main_autoware_system_node_alive
    timeout: 3.0
    # latch: 0.0

  # - path: /foolproof/sub/autoware_node_alive
  #   type: diag
  #   node: autoware_diagnostics_bridge_node_sub
  #   name: sub_autoware_node_alive
  #   timeout: 3.0
  #   latch: 0.0
  - path: /foolproof/perception1/recognition_node_alive
    type: diag
    node: autoware_diagnostics_bridge_node_perception1
    name: perception1_recognition_node_alive
    timeout: 3.0
    # latch: 0.0

  - path: /foolproof/perception2/recognition_node_alive
    type: diag
    node: autoware_diagnostics_bridge_node_perception2
    name: perception2_recognition_node_alive
    timeout: 3.0
    # latch: 0.0

  - path: /foolproof/addon/recognition_node_alive
    type: diag
    node: autoware_diagnostics_bridge_node_addon
    name: addon_recognition_node_alive
    timeout: 3.0
    # latch: 0.0

  - path: /foolproof/addon/camera_driver_node_alive
    type: diag
    node: autoware_diagnostics_bridge_node_addon
    name: addon_camera_driver_node_alive
    timeout: 3.0
    # latch: 0.0

  # scheduling_settings
  - path: /foolproof/main/scheduling_settings_others
    type: diag
    node: autoware_diagnostics_bridge_node_main
    name: main_scheduling_settings_others
    timeout: 3.0
    # latch: 0.0

  - path: /foolproof/main/scheduling_settings_autoware
    type: diag
    node: autoware_diagnostics_bridge_node_main
    name: main_scheduling_settings_autoware
    timeout: 3.0
    # latch: 0.0

  - path: /foolproof/main/update_status_ota
    type: diag
    node: autoware_diagnostics_bridge_node_main
    name: main_update_status_checker_ota
    timeout: 3.0
    # latch: 0.0

  - path: /foolproof/main/update_status_map
    type: diag
    node: autoware_diagnostics_bridge_node_main
    name: main_update_status_checker_map
    timeout: 3.0
    # latch: 0.0

  - path: /foolproof/main/update_status_unrecoverable
    type: diag
    node: autoware_diagnostics_bridge_node_main
    name: main_update_status_checker_ota_unrecoverable
    timeout: 3.0
    # latch: 0.0
