units:
  - path: /map/autonomous_available
    type: and
    list:
      - { type: link, link: /map/emergency_stop }
      - { type: link, link: /map/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /map/in_lane_emergency_stop }
      - { type: link, link: /map/in_lane_moderate_stop }
      - { type: link, link: /map/comfortable_stop }

  - path: /map/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /map/emergency_stop }
      - { type: link, link: /map/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /map/in_lane_emergency_stop }
      - { type: link, link: /map/in_lane_moderate_stop }

  - path: /map/in_lane_moderate_stop_available
    type: and
    list:
      - { type: link, link: /map/emergency_stop }
      - { type: link, link: /map/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /map/in_lane_emergency_stop }

  - path: /map/in_lane_emergency_stop_available
    type: and
    list:
      - { type: link, link: /map/emergency_stop }
      - { type: link, link: /map/sub_ecu_in_lane_moderate_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /map/emergency_stop
    type: and

  - path: /map/comfortable_stop
    type: and

  - path: /map/in_lane_moderate_stop
    type: and

  - path: /map/in_lane_emergency_stop
    type: and

  - path: /map/sub_ecu_in_lane_moderate_stop
    type: and

  - path: /map/none
    type: and
    list:
      - { type: link, link: /map/001-topic_status/vector_map }
      - { type: link, link: /map/001-topic_status/pointcloud_map }

  - path: /map/001-topic_status/vector_map
    type: diag
    node: topic_state_monitor_vector_map
    name: map_topic_status
    timeout: 3.0
    latch: 0.0

  - path: /map/001-topic_status/pointcloud_map
    type: diag
    node: topic_state_monitor_pointcloud_map
    name: map_topic_status
    timeout: 3.0
    latch: 0.0
