units:
  - path: /perception/autonomous_available
    type: and
    list:
      - { type: link, link: /perception/emergency_stop }
      - { type: link, link: /perception/pull_over }
      - { type: link, link: /perception/comfortable_stop }

  - path: /perception/pull_over_available
    type: and
    list:
      - { type: link, link: /perception/emergency_stop }
      - { type: link, link: /perception/comfortable_stop }

  - path: /perception/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /perception/emergency_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /perception/emergency_stop
    type: and
    list:
      - { type: link, link: /perception/001-topic_status/traffic_signals-error }
      - { type: link, link: /perception/001-topic_status/objects-error }
      - { type: link, link: /perception/001-topic_status/pointcloud-error }
      - { type: link, link: /perception/002-detection_delay-error }

  - path: /perception/comfortable_stop
    type: and

  - path: /perception/pull_over
    type: and

  - path: /perception/none
    type: and

  - path: /perception/001-topic_status/traffic_signals-error
    type: warn-to-ok
    item:
      type: link
      link: /perception/001-topic_status/traffic_signals

  - path: /perception/001-topic_status/objects-error
    type: warn-to-ok
    item:
      type: link
      link: /perception/001-topic_status/objects

  - path: /perception/001-topic_status/pointcloud-error
    type: warn-to-ok
    item:
      type: link
      link: /perception/001-topic_status/pointcloud

  - path: /perception/002-detection_delay-error
    type: warn-to-ok
    item:
      type: link
      link: /perception/002-detection_delay

  - path: /perception/001-topic_status/traffic_signals
    type: diag
    node: topic_state_monitor_traffic_light_recognition_traffic_signals
    name: perception_topic_status
    timeout: 1.0

  - path: /perception/001-topic_status/objects
    type: diag
    node: topic_state_monitor_object_recognition_objects
    name: perception_topic_status
    timeout: 1.0

  - path: /perception/001-topic_status/pointcloud
    type: diag
    node: topic_state_monitor_obstacle_segmentation_pointcloud
    name: perception_topic_status
    timeout: 1.0

  - path: /perception/002-detection_delay
    type: diag
    node: multi_object_tracker
    name: Perception delay check from original header stamp
    timeout: 1.0
