units:
  - path: /planning/autonomous_available
    type: and
    list:
      - { type: link, link: /planning/emergency_stop }
      - { type: link, link: /planning/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /planning/in_lane_emergency_stop }
      - { type: link, link: /planning/in_lane_moderate_stop }
      - { type: link, link: /planning/comfortable_stop }

  - path: /planning/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /planning/emergency_stop }
      - { type: link, link: /planning/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /planning/in_lane_emergency_stop }
      - { type: link, link: /planning/in_lane_moderate_stop }

  - path: /planning/in_lane_moderate_stop_available
    type: and
    list:
      - { type: link, link: /planning/emergency_stop }
      - { type: link, link: /planning/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /planning/in_lane_emergency_stop }

  - path: /planning/in_lane_emergency_stop_available
    type: and
    list:
      - { type: link, link: /planning/emergency_stop }
      - { type: link, link: /planning/sub_ecu_in_lane_moderate_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /planning/emergency_stop
    type: and

  - path: /planning/comfortable_stop
    type: and

  - path: /planning/in_lane_moderate_stop
    type: and
    list:
      # - { type: link, link: /planning/000-component_status/route_state }
      - { type: link, link: /planning/003-trajectory_finite_validation-error }
      - { type: link, link: /planning/004-trajectory_interval_validation-error }
      - { type: link, link: /planning/005-trajectory_curvature_validation-error }
      - { type: link, link: /planning/006-trajectory_relative_angle_validation-error }
      - { type: link, link: /planning/007-trajectory_lateral_acceleration_validation-error }
      - { type: link, link: /planning/008-trajectory_acceleration_validation-error }
      - { type: link, link: /planning/009-trajectory_deceleration_validation-error }
      - { type: link, link: /planning/010-trajectory_steering_validation-error }
      - { type: link, link: /planning/011-trajectory_steering_rate_validation-error }
      - { type: link, link: /planning/012-trajectory_velocity_deviation_validation-error }
      # - { type: link, link: /planning/021-incoming_message_timeout }
      - { type: link, link: /planning/013-trajectory_shift_validation-error }
      - { type: link, link: /planning/014-trajectory_validation_yaw_deviation-error }
      - { type: link, link: /planning/017-trajectory_distance_deviation_validation-error }

  - path: /planning/in_lane_emergency_stop
    type: and
    list:
      - { type: link, link: /planning/020-boundary_departure-error }
      - { type: link, link: /planning/016-trajectory_validation_distance_deviation-error }

  - path: /planning/sub_ecu_in_lane_moderate_stop
    type: and

  - path: /planning/none
    type: and
    list:
      - { type: link, link: /planning/015-intersection_collision_checker-error }
      - { type: link, link: /planning/018-rear_collision_checker-error }

  - path: /planning/000-component_status/route_state
    type: diag
    node: /adapi/node/routing
    name: state
    timeout: 1.0

  - path: /planning/003-trajectory_finite_validation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/003-trajectory_finite_validation

  - path: /planning/004-trajectory_interval_validation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/004-trajectory_interval_validation

  - path: /planning/005-trajectory_curvature_validation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/005-trajectory_curvature_validation

  - path: /planning/006-trajectory_relative_angle_validation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/006-trajectory_relative_angle_validation

  - path: /planning/007-trajectory_lateral_acceleration_validation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/007-trajectory_lateral_acceleration_validation

  - path: /planning/008-trajectory_acceleration_validation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/008-trajectory_acceleration_validation

  - path: /planning/009-trajectory_deceleration_validation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/009-trajectory_deceleration_validation

  - path: /planning/010-trajectory_steering_validation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/010-trajectory_steering_validation

  - path: /planning/011-trajectory_steering_rate_validation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/011-trajectory_steering_rate_validation

  - path: /planning/012-trajectory_velocity_deviation_validation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/012-trajectory_velocity_deviation_validation

  - path: /planning/013-trajectory_shift_validation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/013-trajectory_shift_validation

  - path: /planning/014-trajectory_validation_yaw_deviation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/014-trajectory_validation_yaw_deviation

  - path: /planning/015-intersection_collision_checker-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/015-intersection_collision_checker

  - path: /planning/016-trajectory_validation_distance_deviation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/016-trajectory_validation_distance_deviation

  - path: /planning/017-trajectory_distance_deviation_validation-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/017-trajectory_distance_deviation_validation

  - path: /planning/018-rear_collision_checker-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/018-rear_collision_checker

  - path: /planning/020-boundary_departure-error
    type: warn-to-ok
    item:
      type: link
      link: /planning/020-boundary_departure

  - path: /planning/003-trajectory_finite_validation
    type: diag
    node: planning_validator
    name: trajectory_validation_finite
    timeout: 3.0
    # latch: 0.0

  - path: /planning/004-trajectory_interval_validation
    type: diag
    node: planning_validator
    name: trajectory_validation_interval
    timeout: 3.0
    # latch: 0.0

  - path: /planning/005-trajectory_curvature_validation
    type: diag
    node: planning_validator
    name: trajectory_validation_curvature
    timeout: 3.0
    # latch: 0.0

  - path: /planning/006-trajectory_relative_angle_validation
    type: diag
    node: planning_validator
    name: trajectory_validation_relative_angle
    timeout: 3.0
    # latch: 0.0

  - path: /planning/007-trajectory_lateral_acceleration_validation
    type: diag
    node: planning_validator
    name: trajectory_validation_lateral_acceleration
    timeout: 3.0
    # latch: 0.0

  - path: /planning/008-trajectory_acceleration_validation
    type: diag
    node: planning_validator
    name: trajectory_validation_acceleration
    timeout: 3.0
    # latch: 0.0

  - path: /planning/009-trajectory_deceleration_validation
    type: diag
    node: planning_validator
    name: trajectory_validation_deceleration
    timeout: 3.0
    # latch: 0.0

  - path: /planning/010-trajectory_steering_validation
    type: diag
    node: planning_validator
    name: trajectory_validation_steering
    timeout: 3.0
    # latch: 0.0

  - path: /planning/011-trajectory_steering_rate_validation
    type: diag
    node: planning_validator
    name: trajectory_validation_steering_rate
    timeout: 3.0
    # latch: 0.0

  - path: /planning/012-trajectory_velocity_deviation_validation
    type: diag
    node: planning_validator
    name: trajectory_validation_velocity_deviation
    timeout: 3.0
    # latch: 0.0

  - path: /planning/013-trajectory_shift_validation
    type: diag
    node: planning_validator
    name: trajectory_validation_trajectory_shift
    timeout: 3.0
    # latch: 0.0

  - path: /planning/014-trajectory_validation_yaw_deviation
    type: diag
    node: planning_validator
    name: trajectory_validation_yaw_deviation
    timeout: 3.0
    # latch: 0.0

  - path: /planning/015-intersection_collision_checker
    type: diag
    node: planning_validator
    name: intersection_validation_collision_check
    timeout: 3.0
    # latch: 0.0

  - path: /planning/016-trajectory_validation_distance_deviation
    type: diag
    node: planning_validator
    name: trajectory_validation_distance_deviation
    timeout: 3.0
    # latch: 0.0

  - path: /planning/017-trajectory_distance_deviation_validation
    type: diag
    node: planning_validator
    name: trajectory_validation_longitudinal_distance_deviation
    timeout: 3.0
    # latch: 0.0

  - path: /planning/018-rear_collision_checker
    type: diag
    node: planning_validator
    name: rear_collision_check
    timeout: 3.0
    # latch: 0.0

  - path: /planning/020-boundary_departure
    type: diag
    node: motion_velocity_planner
    name: boundary_departure
    timeout: 3.0
    latch: 0.0

  - path: /planning/021-incoming_message_timeout
    type: diag
    node: behavior_path_planner
    name: incoming_message_timeout
    timeout: 3.0
    # latch: 0.0
