units:
  - path: /system/autonomous_available
    type: and
    list:
      - { type: link, link: /system/emergency_stop }
      - { type: link, link: /system/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /system/in_lane_emergency_stop }
      - { type: link, link: /system/in_lane_moderate_stop }
      - { type: link, link: /system/comfortable_stop }

  - path: /system/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /system/emergency_stop }
      - { type: link, link: /system/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /system/in_lane_emergency_stop }
      - { type: link, link: /system/in_lane_moderate_stop }

  - path: /system/in_lane_moderate_stop_available
    type: and
    list:
      - { type: link, link: /system/emergency_stop }
      - { type: link, link: /system/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /system/in_lane_emergency_stop }

  - path: /system/in_lane_emergency_stop_available
    type: and
    list:
      - { type: link, link: /system/emergency_stop }
      - { type: link, link: /system/sub_ecu_in_lane_moderate_stop }

  - path: /system/sub_ecu_in_lane_moderate_stop_available
    type: and
    list:
      - { type: link, link: /system/emergency_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /system/emergency_stop
    type: and

  - path: /system/comfortable_stop
    type: and
    list:
      - { type: link, link: /system/005-daytime_monitor }
      - { type: link, link: /system/002-latency/total-latency-error }

  - path: /system/in_lane_moderate_stop
    type: and
    list:
      - { type: link, link: /system/006-vehicle_stuck_checker }

  - path: /system/in_lane_emergency_stop
    type: and

  - path: /system/sub_ecu_in_lane_moderate_stop
    type: and

  - path: /system/none
    type: and
    list:
      - { type: link, link: /system/012-fms_connection }
      - { type: link, link: /system/013-vcu-not-authenticated }

  - path: /system/002-latency/total-latency-error
    type: warn-to-ok
    item:
      type: link
      link: /system/002-latency/total-latency

  - path: /system/002-latency/total-latency
    type: diag
    node: pipeline_latency_monitor
    name: Total Latency
    timeout: 1.0
    # latch: 0.0

  - path: /system/005-daytime_monitor
    type: diag
    node: daytime_monitor
    name: daytime_status
    timeout: 1.0
    # latch: 0.0

  - path: /system/006-vehicle_stuck_checker
    type: diag
    node: vehicle_stuck_checker
    name: vehicle_stuck_check
    timeout: 3.0
    # latch: 0.0

  - path: /system/012-fms_connection
    type: diag
    node: ""
    name: edge_core_internet_connection
    timeout: 10.0
    # latch: 0.0

  - path: /system/013-vcu-not-authenticated
    type: diag
    node: j6_interface
    name: vcu_not_authenticated
    timeout: 10.0
    # latch: 0.0
