units:
  - path: /vehicle/autonomous_available
    type: and
    list:
      - { type: link, link: /vehicle/emergency_stop }
      - { type: link, link: /vehicle/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /vehicle/in_lane_emergency_stop }
      - { type: link, link: /vehicle/in_lane_moderate_stop }
      - { type: link, link: /vehicle/comfortable_stop }

  - path: /vehicle/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /vehicle/emergency_stop }
      - { type: link, link: /vehicle/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /vehicle/in_lane_emergency_stop }
      - { type: link, link: /vehicle/in_lane_moderate_stop }

  - path: /vehicle/in_lane_moderate_stop_available
    type: and
    list:
      - { type: link, link: /vehicle/emergency_stop }
      - { type: link, link: /vehicle/sub_ecu_in_lane_moderate_stop }
      - { type: link, link: /vehicle/in_lane_emergency_stop }

  - path: /vehicle/in_lane_emergency_stop_available
    type: and
    list:
      - { type: link, link: /vehicle/emergency_stop }
      - { type: link, link: /vehicle/sub_ecu_in_lane_moderate_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /vehicle/emergency_stop
    type: and

  - path: /vehicle/comfortable_stop
    type: and
    list:
      - { type: link, link: /vehicle/007-vehicle-emergency-button }

  - path: /vehicle/in_lane_moderate_stop
    type: and
    list:
      - { type: link, link: /vehicle/001-topic_status/velocity-error }
      - { type: link, link: /vehicle/001-topic_status/steering-error }
      - { type: link, link: /vehicle/006-vehicle_errors-error }
      - { type: link, link: /vehicle/override_when_level4_driving }
      - { type: link, link: /vehicle/t4_vcu_version_check-error }

  - path: /vehicle/in_lane_emergency_stop
    type: and

  - path: /vehicle/sub_ecu_in_lane_moderate_stop
    type: and

  - path: /vehicle/none
    type: and

  - path: /vehicle/001-topic_status/velocity-error
    type: warn-to-ok
    item:
      type: link
      link: /vehicle/001-topic_status/velocity

  - path: /vehicle/001-topic_status/steering-error
    type: warn-to-ok
    item:
      type: link
      link: /vehicle/001-topic_status/steering

  - path: /vehicle/006-vehicle_errors-error
    type: warn-to-ok
    item:
      type: link
      link: /vehicle/006-vehicle_errors

  - path: /vehicle/t4_vcu_version_check-error
    type: warn-to-ok
    item:
      type: link
      link: /vehicle/t4_vcu_version_check

  - path: /vehicle/001-topic_status/velocity
    type: diag
    node: topic_state_monitor_vehicle_status_velocity_status
    name: vehicle_topic_status
    timeout: 1.0
    latch: 0.0

  - path: /vehicle/001-topic_status/steering
    type: diag
    node: topic_state_monitor_vehicle_status_steering_status
    name: vehicle_topic_status
    timeout: 1.0
    latch: 0.0

  - path: /vehicle/006-vehicle_errors
    type: diag
    node: j6_interface
    name: vehicle_errors
    timeout: 1.0
    latch: 0.0

  - path: /vehicle/007-vehicle-emergency-button
    type: diag
    node: j6_interface
    name: vehicle_emergency_button
    timeout: 1.0
    latch: 0.0

  - path: /vehicle/override_when_level4_driving
    type: diag
    node: j6_interface
    name: override_when_level4_driving
    timeout: 1.0
    latch: 0.0

  - path: /vehicle/t4_vcu_version_check
    type: diag
    node: j6_interface
    name: t4_vcu_version_check
    timeout: 2.0
    latch: 0.0
