/**:
  ros__parameters:
    filter_target_label:
      UNKNOWN : true
      CAR : false
      TRUCK : false
      BUS : false
      TRAILER : false
      MOTORCYCLE : false
      BICYCLE : false
      PEDESTRIAN : false

    filter_settings:
      # polygon overlap based filter
      lanelet_xy_overlap_filter:
        enabled: true

      # velocity direction based filter
      lanelet_direction_filter:
        enabled: false
        velocity_yaw_threshold: 0.785398 # [rad] (45 deg)
        object_speed_threshold: 3.0 # [m/s]

      # object's elevation from lanelet based filter
      lanelet_object_elevation_filter:
        enabled: false
        max_elevation_threshold: 5.0 # [m] from a lanelet's surface
        min_elevation_threshold: 0.0 # [m] from a lanelet's surface

      lanelet_extra_margin: 0.0
      debug: false
