base_link:
  sensor_kit_base_link:
    x: 0.9
    y: 0.0
    z: 2.0
    roll: -0.001
    pitch: 0.015
    yaw: -0.0364
  velodyne_rear_base_link:
    x: -0.358
    y: 0.0
    z: 1.631
    roll: -0.02
    pitch: 0.7281317
    yaw: 3.141592
