# This file is managed by workflow.
# Keys marked with '*OVERRIDE*' are persisted as variant overrides.
# If you want to modify a field, make sure that the field has comment including -> # *OVERRIDE*
#
# Source: https://github.com/autowarefoundation/autoware_universe/blob/76922a845358de6042cee56e1e711bf163fdcb23/perception/autoware_lidar_transfusion/config/transfusion_common.param.yaml
# Reference in this repository: .config-sync/perception/autoware_lidar_transfusion/config/transfusion_common.param.yaml

/**:
  ros__parameters:
    diagnostics:
      max_allowed_processing_time_ms: 200.0
      max_acceptable_consecutive_delay_ms: 1000.0
      validation_callback_interval_ms: 100.0
