/**:
  ros__parameters:
    planning_hz: 10.0
    path_length:
      backward: 5.0
      forward: 300.0
    waypoint:
      connection_gradient_from_centerline: 10.0
    turn_signal:
      search_time: 3.0
      search_distance: 30.0
      resampling_interval: 1.0
      angle_threshold_deg: 15.0
    goal_connection:
      connection_section_length: 7.5
      pre_goal_offset: 1.0
