# This file is managed by sync-params workflow.
# Keys marked with '{OVERRIDE}' or '# {OVERRIDE: reason}' are persisted as variant overrides.
# 'reason' can be any single-line text without braces.
# To keep local changes, annotate fields with '# {OVERRIDE}' or '# {OVERRIDE: reason}'.
#
# Source: https://github.com/autowarefoundation/autoware_core/blob/588765440f691cd06db9e552007a0771f2b7e5f2/map/autoware_map_loader/config/lanelet2_map_loader.param.yaml

/**:
  ros__parameters:
    allow_unsupported_version: true             # flag to load unsupported format_version anyway. If true, just prints warning.
    center_line_resolution: 5.0                 # [m]
    use_waypoints: true                         # "centerline" in the Lanelet2 map will be used as a "waypoints" tag.
    lanelet2_map_path: $(var lanelet2_map_path) # The lanelet2 map path
    enable_differential_map_loading: $(var enable_differential_map_loading)      # flag to enable loading of differential map
    lanelet2_map_metadata_path: $(var lanelet2_map_metadata_path) # The lanelet2 map metadata used for differential map loading
