/**:
  ros__parameters:
    # Euclidean clustering
    use_height: false
    tolerance: 0.7
    min_cluster_size: 10
    max_cluster_size: 3000
    voxel_leaf_size: 0.2
    min_points_number_per_voxel: 1
    min_voxel_cluster_size_for_filtering: 10
    max_points_per_voxel_in_large_cluster: 100
    max_voxel_cluster_for_output: 1000

    # Point filtering by semantic confidence
    min_probability: 0.3

    # Semantic label selection and mapping
    # YAML declaration order is treated as the input class_id order.
    # cspell:ignore pullable
    class_names:
      drivable_surface: ignore
      other_flat_surface: ignore
      sidewalk: ignore
      manmade: ignore
      vegetation: ignore
      car: car
      bus: bus
      emergency_vehicle: car
      train: unknown
      truck: truck
      tractor_unit: trailer
      semi_trailer: trailer
      construction_vehicle: truck
      forklift: car
      kart: car
      motorcycle: motorcycle
      bicycle: bicycle
      pedestrian: pedestrian
      personal_mobility: pedestrian
      animal: animal
      pushable_pullable: pedestrian
      traffic_cone: hazard
      debris: hazard
      stroller: pedestrian
      other_stuff: ignore
      noise+ghost_point: ignore

    # Shape estimation behavior
    use_shape_estimation_corrector: false
    use_shape_estimation_filter: false
    use_boost_bbox_optimizer: false
    # 0: ALL_POLYGON, 1: LABEL_DEPEND
    # shape_policy: 0
