# This file is managed by sync-params workflow.
# Keys marked with '{OVERRIDE}' or '# {OVERRIDE: reason}' are persisted as variant overrides.
# 'reason' can be any single-line text without braces.
# To keep local changes, annotate fields with '# {OVERRIDE}' or '# {OVERRIDE: reason}'.
#
# Source: https://github.com/autowarefoundation/autoware_core/blob/cef72e02f92cf21333231db9b247b7d4c85a944d/planning/autoware_core_planning/config/nearest_search.param.yaml

/**:
  ros__parameters:
    # ego
    ego_nearest_dist_threshold: 3.0 # [m]
    ego_nearest_yaw_threshold: 1.046 # [rad] = 60 [deg]
