name: check-config-sync

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    paths:
      - autoware_launch/**

jobs:
  check-config-sync:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ignore-config-sync') }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            autoware_launch/**

      - name: Check config sync
        if: ${{ steps.changed-files.outputs.any_changed == 'true' || steps.changed-files.outputs.any_deleted == 'true' }}
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
          DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
        run: |
          python3 .github/check-config-sync.py
        shell: bash
