name: check-config-sync

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    paths:
      - autoware_launch/**

permissions:
  contents: read
  pull-requests: write

jobs:
  check-config-sync:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ignore-config-sync') }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            autoware_launch/**

      - name: Check config sync
        id: check
        if: ${{ steps.changed-files.outputs.any_changed == 'true' || steps.changed-files.outputs.any_deleted == 'true' }}
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
          DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: python3 .github/check-config-sync.py
        shell: bash

      - name: Post comment
        if: ${{ always() && steps.check.outputs.status == 'mismatch' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: check-config-sync
          path: config-sync-comment.md

      - name: Resolve comment
        if: ${{ always() && steps.check.outputs.status == 'ok' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: check-config-sync
          delete: true
