# This workflow is intended for the use in the repositories created by forking tier4/autoware_launch.
name: sync-beta-upstream

on:
  schedule:
    - cron: 0 20 * * *
  workflow_dispatch:

jobs:
  sync-tier4-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Run sync-branches
        uses: autowarefoundation/autoware-github-actions/sync-branches@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base-branch: beta/<version>
          sync-pr-branch: sync-beta-upstream
          sync-target-repository: https://github.com/tier4/autoware_launch.git
          sync-target-branch: beta/<version>
          pr-title: "chore: sync beta upstream"
          pr-labels: |
            bot
            sync-tier4-upstream
          auto-merge-method: merge
